spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WorkersDB
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.default_schema: workers_schema
  jmx:
    enabled: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb.core: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    root: DEBUG
